image: ubuntu:latest
variables:
  WORK_DIR: gitlab-cicd-tutorial
  REPO: https://gitlab.com/johandurancerdas/gitlab-cicd-tutorial.git
stages:
  - test

test:
  stage: test
  environment: 
    name: Test
    url: "$TST_URL"
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - rm -rf .git
    - ssh -o StrictHostKeyChecking=no ubuntu@"$TST_SERVER" "rm -rf ~/${WORK_DIR}; mkdir ~/${WORK_DIR}; git init; git clone ${REPO}; cd ${WORK_DIR}; git checkout ${CI_COMMIT_REF_NAME}"
