image: ubuntu:latest
stages:
  - test

test:
  stage: test
  environment: 
    name: Test
    url: "$TST_URL"
  when: manual
  before_script:
  - apt-get -qq update && apt-get install -y -qq sshpass
  script:
    - export SSHPASS=$USER_PASS
    - echo "Pulling from current branch"
    - sshpass -e ssh -o StrictHostKeyChecking=no ubuntu@"$TST_SERVER" 'git -C ~/ pull origin master'